export const urtOptions = [
  'botol',
  'buah',
  'bungkus',
  'gelas',
  'ml',
  'piring',
  'potong',
  'potong sedang',
  'sendok makan',
  'sendok nasi',
  'sendok teh'
];

export type FoodRestriction = {
  name: string;
  maxAmount: number;
  unit: string;
};

export type DiseaseRestrictions = {
  [key: string]: FoodRestriction[];
};

export const foodRestrictions: DiseaseRestrictions = {
  diabetes: [
    { name: "nasi", maxAmount: 2, unit: "sendok nasi" },
    { name: "nasi goreng", maxAmount: 1, unit: "sendok makan" },
    { name: "roti putih", maxAmount: 1, unit: "buah" },
    { name: "mie instan goreng", maxAmount: 5, unit: "sendok makan" },
    { name: "mie instan kuah", maxAmount: 5, unit: "sendok makan" },
    { name: "ubi", maxAmount: 1, unit: "buah" },
    { name: "singkong", maxAmount: 1, unit: "potong" },
    { name: "kentang", maxAmount: 1, unit: "buah" },
    { name: "kentang goreng", maxAmount: 3, unit: "biji" },
    { name: "bubur ayam", maxAmount: 10, unit: "sendok makan" },
    { name: "bubur candil", maxAmount: 2, unit: "sendok makan" },
    { name: "bubur sum sum", maxAmount: 3, unit: "sendok makan" },
    { name: "bubur kacang hijau manis", maxAmount: 5, unit: "sendok makan" },
    { name: "Gula", maxAmount: 1, unit: "sendok teh" },
    { name: "jely", maxAmount: 1, unit: "buah" },
    { name: "donat", maxAmount: 2, unit: "buah" },
    { name: "klepon gula merah", maxAmount: 5, unit: "buah" },
    { name: "brownis manis", maxAmount: 1, unit: "potong" },
    { name: "getuk singkong", maxAmount: 1, unit: "biji" },
    { name: "onde-onde", maxAmount: 2, unit: "buah" },
    { name: "pisang coklat", maxAmount: 1, unit: "buah" },
    { name: "kue apem", maxAmount: 1, unit: "buah" },
    { name: "wajik", maxAmount: 1, unit: "buah" },
    { name: "kue putu", maxAmount: 1, unit: "buah" },
    { name: "Bika ambon", maxAmount: 1, unit: "buah" },
    { name: "kue lapis manis", maxAmount: 1, unit: "buah" },
    { name: "kue talam manis", maxAmount: 1, unit: "buah" },
    { name: "roti coklat", maxAmount: 1, unit: "buah" },
    { name: "roti coklat oreo", maxAmount: 1, unit: "buah" },
    { name: "roti meses", maxAmount: 1, unit: "buah" },
    { name: "roti manis", maxAmount: 1, unit: "buah" },
    { name: "Buah manisan", maxAmount: 1, unit: "sendok makan" },
    { name: "the pucuk", maxAmount: 1, unit: "botol" },
    { name: "cocacola", maxAmount: 1, unit: "botol" },
    { name: "jus buah", maxAmount: 2, unit: "gelas" },
    { name: "sprite", maxAmount: 1, unit: "botol" },
    { name: "fanta", maxAmount: 1, unit: "botol" },
    { name: "the botol sosro", maxAmount: 1, unit: "botol" },
    { name: "freste", maxAmount: 1, unit: "botol" },
    { name: "susu boba", maxAmount: 1, unit: "gelas" },
    { name: "Es cream", maxAmount: 1, unit: "bungkus" },
    { name: "jeroan", maxAmount: 2, unit: "sendok makan" },
    { name: "usus", maxAmount: 1, unit: "biji" },
    { name: "paru", maxAmount: 1, unit: "biji" },
    { name: "otak", maxAmount: 2, unit: "sendok makan" },
    { name: "daging goreng", maxAmount: 1, unit: "potong" },
    { name: "daging rendang", maxAmount: 1, unit: "potong" },
    { name: "dendeng daging manis", maxAmount: 1, unit: "potong" },
    { name: "daging berlemak", maxAmount: 1, unit: "potong" },
    { name: "susu full cream", maxAmount: 1, unit: "gelas" },
    { name: "susu kental manis", maxAmount: 1, unit: "sendok makan" },
    { name: "Makanan siap saji", maxAmount: 2, unit: "sendok makan" },
    { name: "seblak", maxAmount: 5, unit: "sendok makan" },
    { name: "bakso", maxAmount: 1, unit: "piring makan" },
    { name: "Cake manis", maxAmount: 1, unit: "buah" },
    { name: "Goreng-gorengan", maxAmount: 1, unit: "buah" },
    { name: "tahu goreng", maxAmount: 2, unit: "buah" },
    { name: "tempe goreng", maxAmount: 2, unit: "buah" },
    { name: "garam dapur,soda,bahan pengawet", maxAmount: 2, unit: "sendok makan" },
    { name: "ikan asin", maxAmount: 1, unit: "potong" },
    { name: "telur asin", maxAmount: 1, unit: "buah" },
    { name: "makanan yang awetkan", maxAmount: 1, unit: "sendok makan" },
    { name: "permen", maxAmount: 1, unit: "buah" },
    { name: "selai", maxAmount: 1, unit: "sendok makan" },
    { name: "manisan buah kedondong", maxAmount: 1, unit: "sendok makan" },
    { name: "rujak buah manis", maxAmount: 2, unit: "sendok makan" },
    { name: "gula merah", maxAmount: 1, unit: "sendok makan" },
    { name: "gula tebu", maxAmount: 1, unit: "sendok makan" },
    { name: "sosis", maxAmount: 1, unit: "buah" },
    { name: "macaroni", maxAmount: 2, unit: "sendok makan" },
    { name: "kuning telur", maxAmount: 1, unit: "buah" },
    { name: "tape", maxAmount: 2, unit: "buah" },
    { name: "dodol", maxAmount: 1, unit: "buah" },
    { name: "coklat", maxAmount: 1, unit: "sendok makan" },
    { name: "sirup", maxAmount: 1, unit: "gelas" },
    { name: "kurma", maxAmount: 2, unit: "buah" },
    { name: "durian", maxAmount: 1, unit: "buah" },
    { name: "ayam opor", maxAmount: 1, unit: "potong" },
    { name: "lontong santan", maxAmount: 5, unit: "sendok makan" },
    { name: "kulit ayam goreng", maxAmount: 1, unit: "sendok makan" }
  ],
  kanker: [
    { name: "Sate Rembiga", maxAmount: 2, unit: "biji" },
    { name: "Sate Tanjung", maxAmount: 2, unit: "biji" },
    { name: "Dendeng Sasak", maxAmount: 2, unit: "potong" },
    { name: "Ayam Taliwang", maxAmount: 1, unit: "potong" },
    { name: "Beberuk Terong", maxAmount: 2, unit: "sendok makan" },
    { name: "Plecing Kangkung", maxAmount: 3, unit: "sendok makan" },
    { name: "Ikan asin sepat", maxAmount: 2, unit: "potong" },
    { name: "Ikan asin teri", maxAmount: 2, unit: "potong" },
    { name: "Abon sapi kemasan", maxAmount: 2, unit: "sendok makan" },
    { name: "Kornet sapi kalengan", maxAmount: 1, unit: "sendok makan" },
    { name: "Sosis kemasan", maxAmount: 1, unit: "potong" },
    { name: "Nugget ayam/frozen", maxAmount: 2, unit: "potong" },
    { name: "Ikan asap", maxAmount: 1, unit: "potong" },
    { name: "Daging sapi olahan kaleng", maxAmount: 2, unit: "sendok makan" },
    { name: "Bakso", maxAmount: 3, unit: "biji" },
    { name: "Tempe goreng tepung", maxAmount: 1, unit: "biji" },
    { name: "Tahu crispy", maxAmount: 1, unit: "biji" },
    { name: "Acar lombok", maxAmount: 2, unit: "sendok makan" },
    { name: "Kentang goreng", maxAmount: 2, unit: "biji" },
    { name: "Telur asin", maxAmount: 1, unit: "butir" },
    { name: "Sambal rembiga instan", maxAmount: 1, unit: "sdm" },
    { name: "Usus ayam goreng", maxAmount: 1, unit: "sendok makan" },
    { name: "Kimchi", maxAmount: 1, unit: "mangkok" },
    { name: "Kulit ayam goreng", maxAmount: 2, unit: "sendok makan" },
    { name: "Pisang sale", maxAmount: 5, unit: "biji" },
    { name: "Mie", maxAmount: 3, unit: "sendok makan" },
    { name: "Kebab", maxAmount: 1, unit: "buah" },
    { name: "Mie goreng bumbu sasak", maxAmount: 3, unit: "sendok makan" },
    { name: "Mie kuah santan pedas", maxAmount: 3, unit: "sendok makan" },
    { name: "Mie telur goreng", maxAmount: 3, unit: "sendok makan" },
    { name: "Manisan mangga", maxAmount: 2, unit: "potong" },
    { name: "Seblak", maxAmount: 3, unit: "sendok makan" },
    { name: "Dodol", maxAmount: 2, unit: "potong" },
    { name: "Kue lapis legit", maxAmount: 2, unit: "potong" },
    { name: "Kue cucur", maxAmount: 1, unit: "buah" },
    { name: "Kue jemblem", maxAmount: 1, unit: "buah" },
    { name: "Donat", maxAmount: 2, unit: "buah" },
    { name: "Kue kering", maxAmount: 2, unit: "buah" },
    { name: "Sirup", maxAmount: 1, unit: "gelas" },
    { name: "Buah kalengan", maxAmount: 1, unit: "gelas" },
    { name: "Tahu goreng", maxAmount: 1, unit: "buah" },
    { name: "Tempe goreng", maxAmount: 1, unit: "buah" },
    { name: "Bakwan goreng", maxAmount: 1, unit: "buah" },
    { name: "Risoles goreng", maxAmount: 1, unit: "buah" },
    { name: "Perkedel goreng", maxAmount: 2, unit: "potong" },
    { name: "Pastel goreng", maxAmount: 1, unit: "buah" },
    { name: "Pisang goreng", maxAmount: 2, unit: "buah" },
    { name: "Keripik", maxAmount: 5, unit: "biji" },
    { name: "Donat goreng", maxAmount: 1, unit: "buah" },
    { name: "Sprite", maxAmount: 0.5, unit: "gelas" },
    { name: "Alkohol", maxAmount: 0.5, unit: "gelas" },
    { name: "Fanta", maxAmount: 0.5, unit: "gelas" },
    { name: "Coca Cola", maxAmount: 0.5, unit: "gelas" },
    { name: "Es boba", maxAmount: 0.5, unit: "gelas" },
    { name: "Bakso kuah", maxAmount: 0.5, unit: "mangkok" },
    { name: "Es ceram", maxAmount: 3, unit: "bungkus" },
    { name: "Kue apem", maxAmount: 2, unit: "buah" },
    { name: "Kue putu", maxAmount: 2, unit: "buah" },
    { name: "Wajik", maxAmount: 1, unit: "buah" },
    { name: "Kelepon", maxAmount: 3, unit: "buah" },
    { name: "Bubur santan", maxAmount: 15, unit: "sendok makan" },
    { name: "Jelly", maxAmount: 2, unit: "cup" },
    { name: "Kopi", maxAmount: 2, unit: "gelas" },
    { name: "Teh", maxAmount: 2, unit: "gelas" },
    { name: "Bakaran", maxAmount: 1, unit: "tusuk" },
    { name: "Roti bakar", maxAmount: 2, unit: "biji" },
    { name: "Lalapan", maxAmount: 2, unit: "porsi" },
    { name: "Sate pusut", maxAmount: 3, unit: "biji" },
    { name: "Ares", maxAmount: 3, unit: "sendok makan" },
    { name: "Empol", maxAmount: 3, unit: "sendok makan" },
    { name: "Sayur nangka santan", maxAmount: 3, unit: "sendok makan" },
    { name: "Urap", maxAmount: 7, unit: "sendok makan" },
    { name: "Asinan buah", maxAmount: 1, unit: "sendok makan" },
    { name: "Rawon", maxAmount: 4, unit: "buah" },
    { name: "Pizza", maxAmount: 2, unit: "potong" },
    { name: "Ayam bakar", maxAmount: 2, unit: "potong" },
    { name: "Daging kambing", maxAmount: 3, unit: "potong" },
    { name: "Kentucky", maxAmount: 2, unit: "potong" },
    { name: "Ayam goreng", maxAmount: 2, unit: "potong" },
    { name: "Seafood", maxAmount: 3, unit: "sendok makan" },
    { name: "Burger", maxAmount: 1, unit: "buah" },
    { name: "Kacang goreng", maxAmount: 5, unit: "sendok makan" },
    { name: "Pepes tai lale", maxAmount: 2, unit: "porsi" }
  ],
  hipertensi: [
    { name: "garam", maxAmount: 1, unit: "sendok teh" },
    { name: "daging sapi", maxAmount: 2, unit: "potong sedang" },
    { name: "abon (daging, ayam, ikan)", maxAmount: 3, unit: "sendok makan" },
    { name: "daging goreng", maxAmount: 2, unit: "potong sedang" },
    { name: "rawon, rendang", maxAmount: 2, unit: "potong sedang" },
    { name: "daging kambing", maxAmount: 2, unit: "potong sedang" },
    { name: "bebek", maxAmount: 2, unit: "potong sedang" },
    { name: "olahan daging (kornet, sosis, bakso, nuget)", maxAmount: 2, unit: "potong sedang" },
    { name: "dendeng sapi", maxAmount: 2, unit: "potong sedang" },
    { name: "jeroan sapi (hati, paru)", maxAmount: 2, unit: "potong sedang" },
    { name: "daging ayam", maxAmount: 2, unit: "potong sedang" },
    { name: "ayam goreng", maxAmount: 2, unit: "potong sedang" },
    { name: "opor ayam, ayam bakar", maxAmount: 2, unit: "potong sedang" },
    { name: "jeroan ayam (hati ampela, usus)", maxAmount: 2, unit: "potong sedang" },
    { name: "kulit ayam", maxAmount: 2, unit: "sendok makan" },
    { name: "olahan ayam (kornet, sosis, bakso, nuget)", maxAmount: 2, unit: "buah" },
    { name: "ikan laut", maxAmount: 2, unit: "potong sedang" },
    { name: "ikan asin", maxAmount: 2, unit: "potong sedang" },
    { name: "ikan kaleng (sarden)", maxAmount: 2, unit: "potong sedang" },
    { name: "ikan teri", maxAmount: 2, unit: "sendok makan" },
    { name: "ikan pindang", maxAmount: 2, unit: "potong sedang" },
    { name: "susu full cream", maxAmount: 100, unit: "ml" },
    { name: "olahan susu (yoghurt)", maxAmount: 3, unit: "sendok makan" },
    { name: "keju", maxAmount: 1, unit: "potong sedang" },
    { name: "mentega", maxAmount: 1, unit: "sendok makan" },
    { name: "margarin", maxAmount: 1, unit: "sendok makan" },
    { name: "cerorot", maxAmount: 2, unit: "buah" },
    { name: "serabi", maxAmount: 3, unit: "buah" },
    { name: "keciput", maxAmount: 4, unit: "buah" },
    { name: "kelepon", maxAmount: 4, unit: "buah" },
    { name: "dadar gulung", maxAmount: 2, unit: "buah" },
    { name: "tempeyek", maxAmount: 2, unit: "buah" },
    { name: "tempani", maxAmount: 2, unit: "buah" },
    { name: "lupis", maxAmount: 3, unit: "buah" },
    { name: "tarek", maxAmount: 3, unit: "buah" },
    { name: "abuk apem", maxAmount: 2, unit: "buah" },
    { name: "poteng", maxAmount: 2, unit: "potong" },
    { name: "wajik", maxAmount: 2, unit: "potong" },
    { name: "renggi", maxAmount: 2, unit: "potong" },
    { name: "dodol", maxAmount: 2, unit: "buah" },
    { name: "gorengan", maxAmount: 3, unit: "potong" },
    { name: "mi", maxAmount: 5, unit: "sendok makan" },
    { name: "bubur", maxAmount: 2, unit: "sendok nasi" },
    { name: "bubur cendil", maxAmount: 3, unit: "sendok makan" },
    { name: "bubur sum sum", maxAmount: 3, unit: "sendok makan" },
    { name: "bubur ketan", maxAmount: 3, unit: "sendok makan" },
    { name: "es krim", maxAmount: 1, unit: "bungkus" },
    { name: "susu kental manis", maxAmount: 2, unit: "sendok makan" },
    { name: "telur goreng", maxAmount: 1, unit: "buah" },
    { name: "telur asin", maxAmount: 1, unit: "buah" },
    { name: "telur pindang", maxAmount: 1, unit: "buah" },
    { name: "telur rebus", maxAmount: 2, unit: "buah" },
    { name: "brownies", maxAmount: 2, unit: "potong" },
    { name: "roti", maxAmount: 1, unit: "buah" },
    { name: "roti coklat", maxAmount: 1, unit: "buah" },
    { name: "roti meses", maxAmount: 1, unit: "buah" },
    { name: "roti keju", maxAmount: 1, unit: "buah" },
    { name: "rujak manis", maxAmount: 1, unit: "piring" },
    { name: "rujak asin", maxAmount: 1, unit: "piring" },
    { name: "ayam geprek", maxAmount: 2, unit: "potong" },
    { name: "tempe goreng", maxAmount: 2, unit: "potong" },
    { name: "tahu goreng", maxAmount: 2, unit: "potong" },
    { name: "makanan siap saji (burger)", maxAmount: 1, unit: "buah" },
    { name: "kebab", maxAmount: 1, unit: "buah" },
    { name: "kentang goreng", maxAmount: 2, unit: "sendok makan" },
    { name: "cimol", maxAmount: 2, unit: "sendok makan" },
    { name: "pizza", maxAmount: 2, unit: "potong" },
    { name: "saus", maxAmount: 1, unit: "sendok makan" },
    { name: "kecap", maxAmount: 1, unit: "sendok makan" },
    { name: "merica", maxAmount: 1, unit: "sendok teh" },
    { name: "sereal", maxAmount: 3, unit: "sendok makan" },
    { name: "selai strowberry", maxAmount: 1, unit: "sendok makan" },
    { name: "selai coklat", maxAmount: 1, unit: "sendok makan" },
    { name: "selai kacang", maxAmount: 1, unit: "sendok makan" },
    { name: "kacang asin", maxAmount: 2, unit: "sendok makan" },
    { name: "minuman soda", maxAmount: 1, unit: "botol" },
    { name: "kopi", maxAmount: 1, unit: "gelas" },
    { name: "the", maxAmount: 2, unit: "gelas" },
    { name: "permen", maxAmount: 2, unit: "buah" },
    { name: "seblak", maxAmount: 2, unit: "sendok makan" },
    { name: "cendol", maxAmount: 1, unit: "gelas" },
    { name: "santan", maxAmount: 1, unit: "gelas" },
    { name: "donat", maxAmount: 2, unit: "buah" },
    { name: "bomboloni", maxAmount: 2, unit: "buah" },
    { name: "keripik singkong", maxAmount: 2, unit: "sendok makan" },
    { name: "buah kaler", maxAmount: 2, unit: "sendok makan" },
    { name: "keripik buah", maxAmount: 2, unit: "sendok makan" },
    { name: "mayonaise", maxAmount: 2, unit: "sendok makan" }
  ]
};
